# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
